你好，我是陈现麟。

通过学习重试幂等的内容，让我们在网络故障和部分失败的分布式系统中，也有办法确保程序之间的调用实现 Exactly-once 的效果，这样当系统出现临时故障的时候，用户依然能正常购买，我们的系统又健壮了一点。

在日常运维极客时间服务端系统的过程中，你一定碰到过大规模故障的情况，可是事后复盘时，却发现故障的起因，大多都是一些局部的小问题引起的，比如因为一个接口响应时间变长，使相关实例的协程或线程数暴涨，让系统的负载进一步增加，最终导致实例所有接口的响应时间都变长，这就从一个接口的局部故障演变成了一个全局的故障。

在一个分布式系统中，局部故障是不可避免的，但是如果不能将局部故障控制好，导致其演变成一个全局的系统故障，这对我们来说是不可以接受的，那么我们应该如何解决这个问题呢？

其实这就是分布式系统中的雪崩场景问题，那么从这节课开始，我们将用四节课的时间来解决，如何让一个分布式系统避免发生雪崩的问题。这一节课，我们先讨论雪崩现象出现的原因，然后再分析如何通过熔断机制来避免雪崩，最后一起总结熔断机制应该注意的关键点。

## 为什么会出现雪崩

雪崩是由于局部故障被正反馈循环，从而导致的不断放大的连锁故障，正如我们上文的例子所说，雪崩通常是由于整个系统中，一个很小的部分出现故障，进而导致系统其他部分也出现故障而引发的。但是，一个正常运行的服务为什么会发生雪崩呢？我认为在实际工作中，出现雪崩一般会经历以下三个阶段，如下图。
<div><strong>精选留言（9）</strong></div><ul>
<li><img src="https://static001.geekbang.org/account/avatar/00/14/59/91/fa2d8bb2.jpg" width="30px"><span>不吃辣👾</span> 👍（5） 💬（2）<div>由于单点过载导致单点机器故障，为了避免全局故障引入了熔断机制。一台机器熔断了，流量打到其他机器上，也会触发其他机器熔断机制，最后还不是整个系统对外不可用。和雪崩有啥区别呢？</div>2022-03-30</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/14/59/91/fa2d8bb2.jpg" width="30px"><span>不吃辣👾</span> 👍（1） 💬（1）<div>老师 如果有两个相同的服务接口，因其保障等级，性能，可用性都不同，是不是将他们分开部署比较合适。同时也避免了雪崩发生。</div>2022-04-07</li><br/><li><img src="http://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTKvNozkiaiao1IyuCzEIMPiaNicB1hgEcad3X4DS6IAq5lnOiagf2690Q7Q1RmyBN89gNqYHeHHtY2RcqQ/132" width="30px"><span>墨龙</span> 👍（0） 💬（1）<div>根据基准环境下对接口的压测数据，提前设定一个阈值，如果队列中的等待数量大于这个数字，就简单认为是过载了。</div>2022-03-08</li><br/><li><img src="http://thirdwx.qlogo.cn/mmopen/vi_32/pZ5ibu3jOPTfWVtzTeNTiaL2PiabGT2Y2yKd2TNDcZMkIY34T5fhGcSnBjgpkd54Q3S6b3gRW3yYTxZk0QHYB0qnw/132" width="30px"><span>啊树</span> 👍（0） 💬（2）<div>请求在队列中的平均等待时间这个指标 -其中的队列是指请求方中准备请求接口的请求么？这个队列是由什么维护的？是tomcat么？ 一般怎么计算这个平均等待时间？</div>2022-02-18</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/10/25/87/f3a69d1b.jpg" width="30px"><span>peter</span> 👍（0） 💬（1）<div>请教老师两个问题：
Q1： “在熔断机制的模式下，服务调用方需要为每一个调用对象，可以是服务、实例和接口，维护一个状态机，在这个状态机中有三种状态：”根据这句话，需要具体的服务来维护状态机，这不合适吧。如果是这样，业务代码岂不是要写很多代码来描述被调用对象？应该是熔断器维护吧。
Q2： 粒度控制部分：
    A “熔断的敏感度高”，敏感度怎么理解？
    B “如果熔断器的阈值大于 10 %，那么将。。。。但是这个结果明显不是我们期待的。”，这段话想说明什么？ 是不是想说“所以，熔断器的阈值不能大于 10 %”</div>2022-02-16</li><br/><li><img src="https://thirdwx.qlogo.cn/mmopen/vi_32/ooYDTtTQHL9CZQmonDOQSC4Af9S4uqicXzUicOqEJqSOtHyOZ81PTpxcTqK5ibNHsaNWJIuHiaVcxB8gIo9RNXsshA/132" width="30px"><span>小叶</span> 👍（0） 💬（1）<div>在断开状态下，会启动一个超时计时器，当计时器超时后，状态切换到半打开状态。什么意思啊</div>2022-02-16</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/17/37/a0/032d0828.jpg" width="30px"><span>上杉夏香</span> 👍（0） 💬（0）<div>我在《Native Cloud Go》这本书上看到的熔断简单示例，Go 语言实现的，大家可以参考一下

type Circuit func(ctx context.Context) (string, error)

func Breaker(circuit Circuit, failerThreshold int) Circuit {
	var (
		consecutiveFailers int
		lastAttempt        = time.Now()
		mu                 sync.RWMutex
	)

	return func(ctx context.Context) (string, error) {
		mu.RLock()

		d := consecutiveFailers - failerThreshold

		if d &gt;= 0 {
            &#47;&#47; 重新尝试的时间点，以上一次尝试的时间点为基础
			shouldRetryAt := lastAttempt.Add(time.Second * 2 &lt;&lt; d) &#47;&#47; exponential backoff algorithm
			if shouldRetryAt.After(time.Now()) {
				mu.RUnlock()
				return &quot;&quot;, errors.New(&quot;service is unreachable&quot;)
			}
		}

		mu.RUnlock()

		resp, err := circuit(ctx)

		mu.Lock()
		defer mu.Unlock()

		lastAttempt = time.Now()

		if err != nil {
			consecutiveFailers++
			return &quot;&quot;, err
		}

		consecutiveFailers = 0 &#47;&#47;  reset failures counter

		return resp, nil
	}
}</div>2023-04-04</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/12/c2/af/ee8cd43d.jpg" width="30px"><span>无情</span> 👍（0） 💬（1）<div>可否再介绍下业界先进的实现熔断机制的中间件？</div>2022-06-23</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/13/17/27/ec30d30a.jpg" width="30px"><span>Jxin</span> 👍（0） 💬（0）<div>答题
1.每次请求带上健康检测请求，实时获取服务端资源使用情况。 高并发场景无效，请求本身都返回不了，更别说追加的健康检测了。

疑问
2.实例接口的熔断，与rpc的故障转移，在作用上存在重复。仔细想想似乎熔断来做更合适。如此一来rpc应该只关注服务是否存活的场景（更新路由列表），而不是接口是否有故障。不知栏主怎么看？</div>2022-02-25</li><br/>
</ul>