你好，我是鸟窝。

共享资源保护、任务编排和消息传递是Go并发编程中常见的场景，而**分组执行一批相同的或类似的任务则是任务编排中一类情形**，所以，这节课，我专门来介绍一下分组编排的一些常用场景和并发原语，包括ErrGroup、gollback、Hunch和schedgroup。

我们先来学习一类非常常用的并发原语，那就是ErrGroup。

# ErrGroup

[ErrGroup](https://github.com/golang/sync/tree/master/errgroup)是Go官方提供的一个同步扩展库。我们经常会碰到需要将一个通用的父任务拆成几个小任务并发执行的场景，其实，将一个大的任务拆成几个小任务并发执行，可以有效地提高程序的并发度。就像你在厨房做饭一样，你可以在蒸米饭的同时炒几个小菜，米饭蒸好了，菜同时也做好了，很快就能吃到可口的饭菜。

ErrGroup就是用来应对这种场景的。它和WaitGroup有些类似，但是它提供功能更加丰富：

- 和Context集成；
- error向上传播，可以把子任务的错误传递给Wait的调用者。

接下来，我来给你介绍一下ErrGroup的基本用法和几种应用场景。

## 基本用法

golang.org/x/sync/errgroup包下定义了一个Group struct，它就是我们要介绍的ErrGroup并发原语，底层也是基于WaitGroup实现的。
<div><strong>精选留言（16）</strong></div><ul>
<li><img src="https://static001.geekbang.org/account/avatar/00/12/4b/69/c02eac91.jpg" width="30px"><span>大漠胡萝卜</span> 👍（5） 💬（1）<div>看了这篇文章还是收获巨大，以前不知道，也没用用过。

首先是，ErrGroup,
官方的实现，bilibili&#47;errgroup，neilotoole&#47;errgroup，facebookgo&#47;errgroup

其它实用的 Group 并发原语SizedGroup&#47;ErrSizedGroup

gollback各种实现，以前在nodejs中经常使用，没想到golang也有实现。
类似的还有Hunch实现。

另外，如果针对定时器比较多的情况，可以使用 schedgroup </div>2020-11-23</li><br/><li><img src="http://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJsOFUdib57ORVyia33dibSGRgwZZ9L2hQ90Xh5WsDUHfpHoCW2AMibnawMLBS6upGH3Qic57kl4PE6v2w/132" width="30px"><span>mbc</span> 👍（3） 💬（2）<div>老师，这种和用普通的go协程或者channel去完成一组任务的编写有啥不一样吗？好处是啥</div>2020-11-28</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/2a/46/e4/0860c82f.jpg" width="30px"><span>东泽</span> 👍（1） 💬（1）<div>文章中多次出现的“让子任务中断执行”，这里的语义是中断子goroutine的执行还是在子goroutine中用类似select &lt;-ctx.Done()的方式在执行任务前判断任务是否应该进行。</div>2021-12-10</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/0f/62/dc/8876c73b.jpg" width="30px"><span>moooofly</span> 👍（1） 💬（2）<div>```go
    ...
    for i := 0; i &lt; total; i++ { &#47;&#47; 并发一万个goroutine执行子任务，理论上这些子任务都会加入到Group的待处理列表中
        go func() {
            g.Go(func(ctx context.Context) error {
                atomic.AddInt64(&amp;count, 1)
                return nil
            })
        }()
    }
	...
```

这个地方有点不理解，g.Go() 不就是创建了子 goroutine 了么，为啥这里还要使用 go func() {...} ；我看文章中其他类似地方都没有这么用，只有这里是这样~</div>2020-11-24</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/10/11/cd/9122abaf.jpg" width="30px"><span>MyronMeng</span> 👍（0） 💬（1）<div>我们应该担心【更进一步，返回所有子任务的错误】这一节：
func main() {
    var g errgroup.Group
    var result = make([]error, 3)    &#47;&#47; 启动第一个子任务,它执行成功
    g.Go(func() error {
        time.Sleep(5 * time.Second)
        fmt.Println(&quot;exec #1&quot;)
        result[0] = nil &#47;&#47; 保存成功或者失败的结果
        return nil    })
       ....
}

这段代码多个 goroutine 写同一个 slice 导致 panic 吗？</div>2023-04-27</li><br/><li><img src="http://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJv3HPde36ll9u5EpEIJyR9jMXE0K7pcuxOlf4HUcbs0po9nkicR0mbXlF1Vdoytj1vxSRCZJGOH7Q/132" width="30px"><span>愤怒的小猥琐</span> 👍（0） 💬（1）<div>errorgroup 49-55 行 为什么要用 go func(){} 去执行 g.Wait() 和 close(ch) 呢，按理说不是应该堵塞等待完成吗？</div>2022-06-13</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/13/0a/65/9cd6d109.jpg" width="30px"><span>秋晨</span> 👍（0） 💬（1）<div>任务执行流水线 Pipeline 的例子第44行，如果处理失败，返回err，当前的goroutine是否会退出呢，如果会退出的话，开启的goroutine数量少于待处理的数据量的话，会不会出现待处理的数据无goroutine处理</div>2021-06-15</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/11/53/ec/3f6ae1aa.jpg" width="30px"><span>皮卡丘</span> 👍（0） 💬（1）<div>cancel，失败的子任务可以 cancel 所有正在执行任务，这句话是不是有点绝对，ctx只是传递信号，如果cancel时，还有子任务的gouroutine没有调度或者内部还没有运行到监听信号才会被cancel掉</div>2020-11-20</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/0f/69/bc/defd41a9.jpg" width="30px"><span>老王</span> 👍（4） 💬（1）<div>使用 errgroup 保存多个错误的代码，运行会报 data race 吧</div>2020-12-16</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/10/30/49/f9e37ced.jpg" width="30px"><span>伟伟</span> 👍（3） 💬（0）<div>package main

import (
	&quot;context&quot;
	&quot;fmt&quot;
	&quot;time&quot;

	&quot;golang.org&#47;x&#47;sync&#47;errgroup&quot;
)

type Data struct {
}

func getData() (*Data, error) {
	time.Sleep(3 * time.Second)
	return &amp;Data{}, nil
}

func main() {
	c, cancel := context.WithCancel(context.Background())
	defer cancel()
	g, ctx := errgroup.WithContext(c)

	datas := make(chan *Data, 10)

	g.Go(func() error {
		&#47;&#47; 业务逻辑
		data, err := getData()
		if err != nil {
			return err
		}

		select {
		case &lt;-ctx.Done():
			return ctx.Err()
		default:
		}
		datas &lt;- data
		return nil
	})

	go func() {
		time.Sleep(1 * time.Second)
		cancel()
	}()

	err := g.Wait()
	if err == nil {
		fmt.Println(&quot;success&quot;)
		return
	}
	fmt.Println(&quot;fail&quot;, err)
}
这里理解的是取消做在业务相关层</div>2020-11-26</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/18/3e/89/77829168.jpg" width="30px"><span>fliyu</span> 👍（1） 💬（0）<div>ErrGroup支持设置并发个数了，即方法SetLimit</div>2022-11-07</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/10/b8/3c/1a294619.jpg" width="30px"><span>Panda</span> 👍（1） 💬（0）<div>CSP 是道   并发原语是术</div>2021-06-15</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/19/55/aa/e05a5778.jpg" width="30px"><span>武安君</span> 👍（1） 💬（0）<div>内容丰富、将我的兵法编程串成了一个脑图！更系统更全！打通了关系图、剩下的就是自己好好研读源码、将技术驱动业务即可！谢谢老师！</div>2021-01-31</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/13/cf/cc/8de5007b.jpg" width="30px"><span>徐改</span> 👍（0） 💬（0）<div>package main

import (
	&quot;context&quot;
	&quot;errors&quot;
	&quot;fmt&quot;
	&quot;sync&quot;
	&quot;time&quot;
)

type errgroupWithCancel struct {
	wg sync.WaitGroup
	errs []string
}

func (egc * errgroupWithCancel) Go(exec func(ctx context.Context), ctx context.Context) {
	egc.wg.Add(1)
	go exec(ctx)
}

func (egc *errgroupWithCancel) Wait() {
	egc.wg.Wait()
}


func main() {
	ctx, cancelFunc := context.WithCancel(context.Background())
	egc := &amp;errgroupWithCancel{wg: sync.WaitGroup{}}
	egc.Go(func(ctx context.Context) {
		defer egc.wg.Done()
		select {
		case &lt;-ctx.Done():
			egc.errs = append(egc.errs, errors.New(&quot;cancel context&quot;).Error())
		case &lt;-time.After(time.Millisecond * 10):
			fmt.Println(&quot;work done&quot;)
		}
	}, ctx)
	time.Sleep(time.Millisecond * 15)
	cancelFunc()
	egc.Wait()
	if len(egc.errs) &gt; 0 {
		for _, err := range egc.errs {
			fmt.Println(err)
		}
	} else {
		fmt.Println(&quot;finish work&quot;)
	}
}
</div>2022-02-12</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/19/22/c8/f2892022.jpg" width="30px"><span>科科</span> 👍（0） 💬（0）<div>很强大，收藏了，之后有时间会把源码都拿出来仔细看看的，真是很强大的工具</div>2021-05-30</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/16/17/6e/76b4aa3d.jpg" width="30px"><span>橙子888</span> 👍（0） 💬（0）<div>打卡。</div>2020-11-20</li><br/>
</ul>